### ISSUE TITLE
How to run spin? FTP Link Misspell

### ISSUE THREAD

**Issue by apinto-helomics** [cmlh-gp/harvestman-public#1]
Hi! I downloaded and tar extracted the harvestman-linux recent release. I have it expanded but I dont see any clear method of utilizing or running the code. Could you provide some installation guidance and commands for the harvestman-linux? 

Edit: I actually have managed to get the tool working, but when I try to spin, during the download of the ftp reference, there appears to be a typo in the link name. 
```
/opt/harvestman-linux/HarvestmanConsole spin -v . -a 38 -o harvest-process -d --ig-cache=None
[15:13:12 INF] Finding VCFs and parsing sample files
[15:13:12 INF] Parsing VCF sample file ./samples.tab
[15:13:12 DBG] Parsed 1 samples from ./samples.tab
[15:13:12 INF] Parsed 1 total samples from all files
[15:13:12 INF] Finished parsing samples (0 MB of memory in-use, step took 00:00:00.0789539, total 00:00:00.0789539 elapsed)
[15:13:12 INF] Parsing VCFs and building variant bitmaps
[15:13:12 INF] Building interval trees for reference genome
[15:13:12 DBG] Downloading http://ftp.ensemblorg.ebi.ac.uk/pub/release-93/gff3/homo_sapiens/Homo_sapiens.GRCh38.93.gff3.gz to /home/apinto/.local/share/harvestman/ref/Homo_sapiens.GRCh38.93.gff3.gz
Unhandled exception. System.Net.Http.HttpRequestException: Name or service not known
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   at Harvestman.Reference.ReferenceDataManager.DownloadFile(String uri, String localPath) in C:\Users\Shawn\code\harvestman\Harvestman\Reference\ReferenceDataManager.cs:line 65
   at Harvestman.Reference.ReferenceDataManager.EnsureExists(String cachedFile) in C:\Users\Shawn\code\harvestman\Harvestman\Reference\ReferenceDataManager.cs:line 41
   at Harvestman.Reference.Genome.FileFeatureCache.GetFeaturesAsync(Int32 majorVersion, ISet`1 optionalSeqIdWhitelist) in C:\Users\Shawn\code\harvestman\Harvestman\Reference\Genome\FeatureCache.cs:line 29
   at Harvestman.Reference.Genome.GffIntervalTreeBuilder.BuildByLocation(Int32 assemblyVersion, ISet`1 seqIdWhitelist) in C:\Users\Shawn\code\harvestman\Harvestman\Reference\Genome\GffIntervalTreeBuilder.cs:line 21
   at Harvestman.Spinning.Variants.PipelinedVariantProcessor.Process[T](FilesystemVariantRoot variantSources, IEnumerable`1 allSampleIds, Func`1 sinkGenerator, Int32 assemblyVersion, IEnumerable`1 snpVcfFiles, ISet`1 seqIdWhitelist) in C:\Users\Shawn\code\harvestman\Harvestman\Spinning\Variants\PipelinedVariantProcessor.cs:line 38
   at Harvestman.Spinning.MsgPack.MsgPackSpinner.Spin(IEnumerable`1 inputDirectories, String outputDirectory, Int32 assemblyVersion, Boolean shuffle, Int32 shuffleSeed, String defaultLabel, RelevanceCacheType cacheType, IEnumerable`1 snpVcfFiles, IEnumerable`1 sequenceIds) in C:\Users\Shawn\code\harvestman\Harvestman\Spinning\MsgPack\MsgPackSpinner.cs:line 69
   at HarvestmanConsole.Program.Spin(SpinOptions opts) in C:\Users\Shawn\code\harvestman\HarvestmanConsole\Program.cs:line 44
   at HarvestmanConsole.Program.Main(String[] args) in C:\Users\Shawn\code\harvestman\HarvestmanConsole\Program.cs:line 27
   at HarvestmanConsole.Program.<Main>(String[] args)
Aborted
```

**Comment by apinto-helomics** [comment]
For example http://ftp.ensembl.org/pub/release-93/gff3/homo_sapiens/ exists, but http://ftp.ensemblorg.ebi.ac.uk/pub/release-93/gff3/homo_sapiens/ does not

**Comment by sjbaker47** [comment]
Hi @apinto-helomics! I've published a pre-release version with the URLs fixed (they must have changed in the past year.) You can see it at:

https://github.com/cmlh-gp/harvestman-public/releases/tag/url-revision

Let me know if you need anything else.

**Comment by apinto-helomics** [comment]
Hi again! 

I am trying to get a neo4j output, but whenever I run the spin command, it states the the VCF samples.tab doesnt have a header. However, when i run the same command with the same samples.tab file with the default output, the samples.tab can be parseed easily and spin completes. 

```
$/opt/harvestman-linux/HarvestmanConsole spin -v . -a 38 -o harvest-process-neo4j -d --ig-cache=None -f neo4j --log-file first_harvestman_spin.log
[09:14:41 INF] Exporting reference data to neo4j-import CSV
[09:14:41 INF] Exporting GO data to neo4j-import CSV
[09:14:42 INF] Gathering data about the reference genome...
[09:15:54 INF] Writing out sample file to neo4j-import CSV
[09:15:54 INF] Parsing ./samples.tab and outputting neo4j-import CSV at harvest-process-neo4j/samples.csv
[09:15:54 INF] Finished writing sample file neo4j-import CSV
[09:15:54 INF] Starting process of converting VCFs to neo4j-import CSV
[09:15:54 INF] Doing bulk conversion of VCF files to neo4j-import native CSV to harvest-process-neo4j
[09:15:54 INF] Building interval tree against reference genome...
[09:16:54 INF] Writing out CSV files...
[09:16:54 INF] Parsing ./samples.tab
[09:16:54 ERR] VCF samples.tab doesn't have a header!
[09:16:54 DBG] Finished parsing VCF files!
[09:16:54 DBG] Waiting for CSV writers to finish
[09:16:54 INF] Finished writing CSV files!
[09:16:54 INF] Finished converting VCFs to neo4j-import CSV
[09:16:54 DBG] Writing out argument file to harvest-process-neo4j/neo4j_arguments
[09:16:54 INF] Finished conversion of VCF to neo4j-import format!
[09:16:54 INF] Run the following command to import your data: neo4j-admin import -f 'harvest-process-neo4j/neo4j_arguments'
``` 
Here is the same command, same directory same samples.tab file but without the -f neo4j flag:
```
/opt/harvestman-linux/HarvestmanConsole spin -v . -a 38 -o harvest-process-neo4j -d --ig-cache=None --log-file first_harvestman_spin-msg.log
[09:17:28 INF] Finding VCFs and parsing sample files
[09:17:29 INF] Parsing VCF sample file ./samples.tab
[09:17:29 DBG] Parsed 2505 samples from ./samples.tab
[09:17:29 INF] Parsing VCF sample file ./harvest-process-neo4j/samples.csv
[09:17:29 DBG] Parsed 2505 samples from ./harvest-process-neo4j/samples.csv
[09:17:29 INF] Parsed 5010 total samples from all files
[09:17:29 INF] Finished parsing samples (1 MB of memory in-use, step took 00:00:00.2374597, total 00:00:00.2374597 elapsed)
....etc
```
Does the samples.tab file need to be different for the neo4j command? Could you possibly provide an example of the expected structure?

**Comment by sjbaker47** [comment]
I would say that neo4j mode isn't really supported -- the MessagePack mode of operation is faster and more feature complete. If you have a particular use case for Neo4j in mind, let me know in another issue!

**Comment by apinto-helomics** [comment]
Thank you!
